spring:
  data:
    cassandra:
      # NONE, CREATE, CREATE_IF_NOT_EXISTS
      schema-action: NONE
      request.timeout: 10s
      connection.connect-timeout: 10s
      connection.init-query-timeout: 10s

      local-datacenter: datacenter1
      contactPoints: localhost:9042
      keyspace-name: geps
      username: cassandra
      password: cassandra
