config: dev

# This is config-specific configuration for dev env
oidc:
  providers:
    # Facebook test provider
    facebook:
      clientId: '558989508631164'

  # redirectUrl is backend-signed totemftc.bbs.io that is processed by flutter router
  redirectUrl: http://localhost

  # web redirectUrl is static html page that closes popup and callback original page
  redirectUrlWeb: http://localhost:8082/login-callback.html

backendUrl: http://localhost:8080
